# Generated by Django 3.1 on 2020-08-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, verbose_name='Currency Code')),
                ('currency_value', models.FloatField(verbose_name='Currency Value')),
            ],
        ),
    ]
