# Generated by Django 3.1 on 2020-08-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='currency_value',
        ),
        migrations.AddField(
            model_name='currency',
            name='counts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
